# Generated by Django 5.0.1 on 2024-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cardnumber', models.CharField(max_length=16)),
                ('cvv', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=5)),
                ('holdername', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
