# Generated by Django 5.0.1 on 2024-06-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cardpayment_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpayment',
            name='cardnumber',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cardpayment',
            name='holdername',
        ),
    ]
